language: php
php:
    - 7.0

script:
    - vendor/bin/tester tests/

before_script:
    - travis_retry composer install --no-interaction --prefer-dist

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

